### ISSUE TITLE
about组合数学期末

### ISSUE THREAD

**Issue by huangchenzhao** [guch8017/USTC_CS_EXAM#3]
请问大佬还有组合数学期末的往年试卷吗？或者想问一下大佬组合数学期中的试卷是从什么渠道得到的，我去相同的渠道找一下。万分感谢。

**Comment by guch8017** [comment]
期中是当时查卷的时候拍的重新打的，期末没这个环节就没了

**Comment by huangchenzhao** [comment]
> 期中是当时查卷的时候拍的重新打的，期末没这个环节就没了

好的，谢谢
